version: 1
# Active split label to serve; must match a label defined in globals.split.
# Set to null to disable filtering or override per run via CLI.
keep: train
# Optional defaults for jerry serve (override via CLI when needed).
output: print # print | stream | /path/to/file.pt
limit: 100 # max vectors per serve run (null = unlimited)
include_targets: false # serve dataset.targets alongside features
throttle_ms: null # milliseconds to sleep between emitted vectors
verbosity: 1 # 0 output only, 1=spinner+prints, 2=progress bars
