version: 1
# Active split label to serve; must match a label defined in globals.split.
# Set to null to disable filtering or override per run via CLI.
keep: train
# Optional defaults for jerry run serve/prep (override via CLI when needed).
output: print          # print | stream | /path/to/file.pt
limit: 100             # max vectors per serve/prep run (null = unlimited)
include_targets: false # serve dataset.targets alongside features
throttle_ms: null      # milliseconds to sleep between emitted vectors
visuals: null          # set true to enable visuals, false to disable, null to use command defaults
