group_by:
  keys:
    - type: time
      field: time
      resolution: 1h

features:
  - id: time
    stream: time_ticks
    transforms:
      - record:
          filter: ge
          args:
            time: 2021-01-01T00:00:00Z
      - record:
          transform: time_lag
          args: 1h
      - feature:
          transform: standard_scale
          with_mean: true
          with_std: true

# Optional feature-level fills (uncomment to enable)
#      - sequence:
#          transform: time_fill_median
#          window: 24
#          min_samples: 4

# Optional vector-level adjustments applied after merging partitions
# vector_transforms:
#   - fill_history:
#       expected:
#         - time
#       statistic: median
#       window: 48
#       min_samples: 6
#   - fill_horizontal:
#       manifest: config/recipes/default/build/partitions.json
#       statistic: mean
#       min_samples: 2
#   - drop_missing:
#       manifest: config/recipes/default/build/partitions.json
#       min_coverage: 0.9
targets:
  - id: time
    stream: time_ticks
