group_by:
  keys:
    - type: time
      field: time
      resolution: 1h

features:
  - id: time
    stream: time_ticks
    transforms:
      - record:
          filter: ge
          args:
            time: 2021-01-01T00:00:00Z
      - record:
          transform: time_lag
          args: 1h
      - feature:
          transform: standard_scale
          with_mean: true
          with_std: true

# Optional vector-level clean-up
# vector_cleaning:
#   - transform: drop_incomplete
#     manifest: config/recipes/default/build/partitions.json
#     min_coverage: 0.9
#   - transform: fill_missing
#     manifest: config/recipes/default/build/partitions.json
#     strategy: constant
#     value: 0.0

targets:
  - id: time
    stream: time_ticks
