# See ../../../reference/reference/tasks/operations/inspect.reference.yaml for full options.
id: coverage
kind: runtime
entrypoint: core.runtime.coverage
runtime_kind: inspect
dependencies:
  - stats
  - metadata
options:
  sort: missing
