# See ../../../reference/reference/tasks/operations/inspect.reference.yaml for full options.
id: matrix
entrypoint: core.inspect.matrix
dependencies:
  - stats
  - metadata
options:
  format: html
  quiet: true
