# See ../../../reference/reference/tasks/operations/pipeline.reference.yaml for full options.
id: pipeline
kind: runtime
entrypoint: core.runtime.pipeline
runtime_kind: serve
dependencies:
  - schema
  - metadata
  - scaler
