# See ../../../../plugin_skeleton/reference/reference/tasks/operations/inspect.reference.yaml for full options.
id: coverage
entrypoint: core.inspect.coverage
dependencies:
  - stats
  - metadata
options:
  sort: missing
