# See ../../../../plugin_skeleton/reference/reference/tasks/operations/inspect.reference.yaml for full options.
id: matrix
kind: runtime
entrypoint: core.runtime.matrix
runtime_kind: inspect
dependencies:
  - stats
  - metadata
options:
  format: html
  quiet: true
