# See ../../../../plugin_skeleton/reference/reference/tasks/operations/inspect.reference.yaml for full options.
id: matrix
entrypoint: core.inspect.matrix
dependencies:
  - schema
  - metadata
  - scaler
options:
  mode: final
  format: html
  quiet: true
