# See ../../../../plugin_skeleton/reference/reference/tasks/operations/stats.reference.yaml for full options.
id: stats
kind: artifact
entrypoint: core.artifact.stats
dependencies:
  - metadata
  - scaler
mode: final
