# See ../../../../plugin_skeleton/reference/reference/tasks/operations/inspect.reference.yaml for full options.
id: thresholds
kind: runtime
entrypoint: core.runtime.thresholds
options:
  sort: missing
  threshold: 0.95
