# See ../../../../plugin_skeleton/reference/reference/tasks/operations/inspect.reference.yaml for full options.
id: thresholds
entrypoint: core.inspect.thresholds
dependencies:
  - stats
  - metadata
options:
  sort: missing
  threshold: 0.95
