group_by: 1h

features:
  - id: time
    record_stream: time_hour_sin
    # scale: { with_mean: true, with_std: true }
    # sequence: { size: 6, stride: 1, tick: 10m }

  # - id: second_feature
  #   record_stream: anotherstream
# targets:
#   - id: some_target
#     record_stream: time_linear

