# - drop_missing:
#     # require these features present OR set min_coverage below
#     required: [time]
#     min_coverage: 1.0
# - fill_constant:
#     value: 0.0
# - fill_history:
#     statistic: median
#     window: 48
#     min_samples: 6
# - fill_horizontal:
#     statistic: mean
#     min_samples: 2
