SOURCE_KEY = "source"
DEFAULT_IO_LOADER_EP = "core.io"
DEFAULT_SYNTHETIC_LOADER_EP = "core.synthetic.ticks"
DEFAULT_TEMPORAL_RECORD_PARSER_EP = "core.temporal_record"

SCALER_STATISTICS = "scaler"
VECTOR_SCHEMA = "schema"
VECTOR_METADATA = "metadata"
VECTOR_STATS = "stats"
VECTOR_INPUTS = "vector_inputs"
