PARSER_KEY = "parser"
LOADER_KEY = "loader"
SOURCE_KEY = "source"
SOURCE_ID_KEY = "id"
MAPPER_KEY = "mapper"
ENTRYPOINT_KEY = "entrypoint"
ARGS_KEY = "args"
STREAM_ID_KEY = "id"
STREAM_FROM_KEY = "from"
STREAM_CADENCE_KEY = "cadence"
STREAM_KIND_KEY = "kind"
POSTPROCESS_PATH_KEY = "postprocess"

PARSERS_GROUP = "parsers"
LOADERS_GROUP = "loaders"
MAPPERS_GROUP = "mappers"
FILTERS_GROUP = "filters"
DEFAULT_IO_LOADER_EP = "core.io"
DEFAULT_SYNTHETIC_LOADER_EP = "core.synthetic.ticks"
DEFAULT_TEMPORAL_RECORD_PARSER_EP = "core.temporal_record"

POSTPROCESS_TRANSFORMS = "transforms"
SCALER_STATISTICS = "scaler"
VECTOR_SCHEMA = "schema"
VECTOR_METADATA = "metadata"
VECTOR_STATS = "stats"
VECTOR_INPUTS = "vector_inputs"
