PARSERS_EP = "datapipeline.parsers"
LOADERS_EP = "datapipeline.loaders"
MAPPERS_EP = "datapipeline.mappers"
BUILD_OPERATIONS_EP = "datapipeline.operations.build"
RUNTIME_OPERATIONS_EP = "datapipeline.operations.runtime"
