source_id: time_ticks

parser:
  entrypoint: synthetic.time
  args: {}
loader:
  entrypoint: synthetic.time
  args:
    start: "2024-01-01T00:00:00Z"
    end:   "2024-01-01T03:00:00Z"
    frequency: "1h"
