# See ../../../reference/reference/tasks/profiles/serve.reference.yaml for full options.
kind: serve
name: all
target: serve
keep: null
output:
  transport: fs
  format: jsonl
  directory: data/interim/jerry
