# See ../reference/reference/project.yaml for full options.
version: 1
name: <your-dataset>
paths:
  streams: ./contracts
  sources: ./sources
  dataset: dataset.yaml
  postprocess: postprocess.yaml
  artifacts: ../artifacts/${project_name}/v${version}
  tasks: ./tasks
globals:
  group_by: <your-bucket-cadence>
  start_time: null
  end_time: null
  split:
    mode: hash
    key: group
    seed: 42
    ratios: { train: 0.8, val: 0.1, test: 0.1 }
