name: Publish to TestPyPI (Trusted Publisher)

on:
  push:
    tags:
      - "v*.*.*-rc*" # example: publish release candidates to TestPyPI

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-testpypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
