name: Publish to PyPI (Trusted Publisher)

on:
  release:
    types: [published] # run when you publish a GitHub Release

permissions:
  id-token: write # REQUIRED for OIDC trust with PyPI
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi # matches the “Environment name” you set on PyPI
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tooling
        run: python -m pip install --upgrade pip build

      - name: Build sdist & wheel
        run: python -m build

      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
